# Generated by Django 6.0.2 on 2026-03-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donationsubject_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationsubject',
            options={'ordering': ['-is_default', 'name']},
        ),
    ]
