# Generated by Django 5.2.1 on 2026-02-10 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='news',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='news.category'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status'], name='news_news_status_b581f2_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published_at'], name='news_news_publish_377f0e_idx'),
        ),
    ]
