# Generated by Django 5.2.1 on 2026-02-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_memberdetail_created_by_and_more'),
        ('news', '0002_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to='member.member'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_updated', to='member.member'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
