# Generated by Django 5.2.1 on 2026-02-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_news_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_review_news", "Can review member news (publish/reject)")],
                "verbose_name_plural": "News",
            },
        ),
    ]
