# Generated by Django 6.0.2 on 2026-02-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0010_memberpasswordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/albums/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('protected', 'Protected (Logged In Users)'), ('private', 'Private (Owner Only)')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('inreview', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_albums', to='member.member')),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'verbose_name_plural': 'Gallery Albums',
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('can_review_gallery', 'Can review member gallery albums')],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.galleryalbum')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['status'], name='gallery_gal_status_99ea79_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['visibility'], name='gallery_gal_visibil_dbd3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryalbum',
            index=models.Index(fields=['published_at'], name='gallery_gal_publish_4e997b_idx'),
        ),
    ]
