# Generated by Django 6.0.2 on 2026-02-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inreview', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='inreview', max_length=12),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['status'], name='gallery_gal_status_88b341_idx'),
        ),
    ]
