# Generated by Django 6.0.2 on 2026-03-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_published_at_galleryimage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected (Logged In Users)'), ('private', 'Private (Owner Only)')], default='public', max_length=20),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['visibility'], name='gallery_gal_visibil_6ca5a8_idx'),
        ),
    ]
