# Generated by Django 6.0.2 on 2026-03-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryimage_visibility_and_more'),
        ('member', '0022_alter_memberdetail_matrimonial_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(blank=True, help_text="The ID of the 'bb_album' folder", max_length=255, null=True)),
                ('credentials_data', models.TextField(blank=True, help_text='Serialized OAuth2 credentials', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_connection', to='member.member')),
            ],
            options={
                'verbose_name': 'Google Drive Connection',
                'verbose_name_plural': 'Google Drive Connections',
            },
        ),
    ]
