# Generated by Django 6.0.2 on 2026-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_googledriveconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
