# Generated by Django 6.0.2 on 2026-03-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_galleryalbum_google_drive_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
