# Generated by Django 5.2.1 on 2026-02-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0005_alter_memberdetail_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('desc', models.TextField()),
                ('categories', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('rental', 'Rental')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=50)),
                ('approx_range_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approx_range_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bns_created', to='member.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bns_updated', to='member.member')),
            ],
            options={
                'verbose_name': 'BNS Model',
                'verbose_name_plural': 'BNS Models',
                'db_table': 'bns_model',
                'ordering': ['-created_at'],
            },
        ),
    ]
