# Generated by Django 5.2.1 on 2026-02-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bnsmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'BNS', 'verbose_name_plural': 'BNS'},
        ),
    ]
