# Generated by Django 5.2.1 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_bnsmodel_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bnsmodel",
            old_name="categories",
            new_name="listing_type",
        ),
        migrations.RenameField(
            model_name="bnsmodel",
            old_name="approx_range_from",
            new_name="min_price",
        ),
        migrations.RenameField(
            model_name="bnsmodel",
            old_name="approx_range_to",
            new_name="max_price",
        ),
        migrations.AlterField(
            model_name="bnsmodel",
            name="listing_type",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller"), ("rental", "Rental")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bnsmodel",
            name="min_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bnsmodel",
            name="max_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bnsmodel",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
