# Generated by Django 5.2.1 on 2026-02-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_fields_and_add_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnsmodel',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bnsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/images/'),
        ),
        migrations.AddField(
            model_name='bnsmodel',
            name='updated_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
