# Generated by Django 5.2.1 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_bnsmodel_created_by_username_bnsmodel_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bnsmodel",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE bns_model SET published_at = created_at WHERE published_at IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="bnsmodel",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterModelOptions(
            name="bnsmodel",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "BNS",
                "verbose_name_plural": "BNS",
            },
        ),
    ]
