# Generated by Django 5.2.1 on 2026-02-16

from django.db import migrations, models


def set_existing_rows_published(apps, schema_editor):
    BnsModel = apps.get_model("marketplace", "BnsModel")
    BnsModel.objects.all().update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_bnsmodel_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bnsmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("inreview", "In Review"),
                    ("published", "Published"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.RunPython(
            set_existing_rows_published,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="bnsmodel",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
