# Generated by Django 5.2.1 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_bnsmodel_status_and_publish_logic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bnsmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("inreview", "In Review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
    ]
