# Generated by Django 6.0.2 on 2026-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_bnsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnsmodel',
            name='bidding_enabled',
            field=models.BooleanField(default=False, help_text='Enable bidding for this item'),
        ),
    ]
