# Generated by Django 6.0.2 on 2026-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_winner',
            field=models.BooleanField(default=False, help_text='Mark this bid as the winning bid'),
        ),
    ]
