# Generated by Django 6.0.2 on 2026-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_bid_is_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnsmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inreview', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('sold', 'Sold')], default='draft', max_length=12),
        ),
    ]
