# Generated by Django 5.2.1 on 2026-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_memberdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
