# Generated by Django 5.2.1 on 2026-02-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberdetail_created', to='member.member'),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberdetail_updated', to='member.member'),
        ),
    ]
