# Generated by Django 6.0.2 on 2026-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_memberpasswordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='about_matrimonial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='annual_income',
            field=models.CharField(blank=True, help_text='e.g. 5-7 LPA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='gotra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='height',
            field=models.CharField(blank=True, help_text='e.g. 5\'7"', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='is_matrimonial_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='manglik',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='matrimonial_photo',
            field=models.ImageField(blank=True, null=True, upload_to='member/matrimonial/'),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='relation_with_member',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('relative', 'Relative')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='show_on_matrimonial',
            field=models.BooleanField(default=False),
        ),
    ]
