# Generated by Django 6.0.2 on 2026-03-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_memberdetail_about_matrimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='community',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Public contact number for matrimonial', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='diet',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian'), ('vegan', 'Vegan'), ('jain', 'Jain')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='family_type',
            field=models.CharField(blank=True, choices=[('nuclear', 'Nuclear'), ('joint', 'Joint'), ('extended', 'Extended')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='family_values',
            field=models.CharField(blank=True, choices=[('traditional', 'Traditional'), ('moderate', 'Moderate'), ('liberal', 'Liberal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='full_bio',
            field=models.TextField(blank=True, help_text='Detailed biodata', null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='partner_preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='religion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='siblings',
            field=models.CharField(blank=True, help_text='e.g. 1 younger sister (married)', max_length=200, null=True),
        ),
    ]
