# Generated by Django 6.0.2 on 2026-03-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_memberdetail_community_memberdetail_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetail',
            name='community',
        ),
        migrations.RemoveField(
            model_name='memberdetail',
            name='family_values',
        ),
        migrations.RemoveField(
            model_name='memberdetail',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='memberdetail',
            name='religion',
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='addictions',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly'), ('prefer_not_to_say', 'Prefer not to say')], help_text='e.g. Smoking, Drinking', max_length=50, null=True),
        ),
    ]
