# Generated by Django 6.0.2 on 2026-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_remove_memberdetail_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='addictions',
            field=models.CharField(blank=True, help_text='e.g. Smoke, Drink (comma separated)', max_length=200, null=True),
        ),
    ]
