# Generated by Django 6.0.2 on 2026-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_alter_memberdetail_addictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='diet',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('swaminarayan', 'Swaminarayan'), ('non_vegetarian', 'Non-Vegetarian'), ('eggetarian', 'Eggetarian'), ('vegan', 'Vegan'), ('jain', 'Jain')], max_length=20, null=True),
        ),
    ]
