# Generated by Django 6.0.2 on 2026-03-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_memberdetail_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
