# Generated by Django 6.0.2 on 2026-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_memberdetail_is_protected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetail',
            name='is_protected',
        ),
        migrations.AddField(
            model_name='member',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected')], default='Public', help_text='Public: visibly to anyone. Protected: visible to logged-in users only.', max_length=20),
        ),
    ]
