# Generated by Django 6.0.2 on 2026-03-23 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_remove_memberdetail_is_protected_member_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='visibility',
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='matrimonial_visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected')], default='Public', help_text='Public: show to all without login. Protected: show to logged in users.', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The admin user who approved this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Inactive', max_length=20),
        ),
    ]
