# Generated by Django 6.0.2 on 2026-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='matrimonial_visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected'), ('Private', 'Private')], default='Public', help_text='Public: show to all without login. Protected: show to logged in users. Private: owner only.', max_length=20),
        ),
    ]
