# Generated by Django 6.0.2 on 2026-03-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_alter_memberdetail_matrimonial_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='matrimonial_visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected (Logged In Users)'), ('Private', 'Private (Owner Only)')], default='Public', help_text='Public: show to all. Protected: logged in users only. Private: owner only.', max_length=20),
        ),
    ]
