# Generated by Django 6.0.2 on 2026-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_alter_memberdetail_matrimonial_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='matrimonial_visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected')], default='Public', help_text='Public: show to all without login. Protected: show to logged in users.', max_length=20),
        ),
    ]
