# Generated by Django 5.2.1 on 2026-01-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_member_memberdetail_delete_memeber'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='member_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='member.member'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
