# Generated by Django 5.2.1 on 2026-01-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_memberdetail_member_no_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberDetail',
        ),
    ]
