# Generated by Django 6.0.2 on 2026-03-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0010_memberpasswordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon for the category', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Business Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('service', models.CharField(help_text='Service type or specialization', max_length=255)),
                ('location', models.CharField(help_text='City or area', max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, help_text='Description of services offered')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business/images/')),
                ('address', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.CharField(blank=True, help_text='e.g., 9 AM - 6 PM', max_length=255)),
                ('price_range_min', models.IntegerField(blank=True, null=True)),
                ('price_range_max', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('inreview', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_created', to='member.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_updated', to='member.member')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='business.businesscategory')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'business',
                'ordering': ['-published_at'],
                'permissions': [('can_review_business', 'Can review member business (publish/reject)')],
                'indexes': [models.Index(fields=['status'], name='business_status_6097ca_idx'), models.Index(fields=['published_at'], name='business_publish_4a59ae_idx')],
            },
        ),
    ]
